@startuml
|SPA|
start
:login button;
:Show login options;
|Auth provider (Redirect)|
:Go to 3rd party login page;
:User authorize;
|Server (Redirect)|
:go to redirect uri;
:Load the user profile;
|SPA|
:reload application
to previous page;
stop
@enduml